services:
  spark-master:
    image: spark:3.5.0-java17-python3
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.master.Master","--host","spark-master","--port","7077","--webui-port","8080"]
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - ./data:/opt/spark/work-dir/data
    restart: unless-stopped

  spark-worker-1:
    image: spark:3.5.0-java17-python3
    container_name: spark-worker-1
    command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.worker.Worker","--cores","2","--memory","3g","--webui-port","8081","spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - ./data:/opt/spark/work-dir/data
    restart: unless-stopped

  spark-worker-2:
    image: spark:3.5.0-java17-python3
    container_name: spark-worker-2
    command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.worker.Worker","--cores","2","--memory","3g","--webui-port","8082","spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - ./data:/opt/spark/work-dir/data
    restart: unless-stopped

  spark-jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark-jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=spark
    ports:
      - "8888:8888"
    volumes:
      - ./apps:/home/jovyan/apps
      - ./data:/home/jovyan/data
      - ./apps:/opt/spark/work-dir/apps
      - ./data:/opt/spark/work-dir/data
    depends_on:
      - spark-master
    restart: unless-stopped
